project:
  type: book
  output-dir: docs
  

book:
  title: "Schmidt Ocean Institute Technical Documentation"
  output-file: "Schmidt-Ocean-Institute-Technical-Documentation"
  author: "Schmidt Ocean Institute"
  favicon: /images/fcs_soibrand_variation3_fullcolorsoibrand_variation3_fullcolor@10x.png
  date: "5/22/2023"
  search: true
  repo-url: https://github.com/schmidtocean/public_technical_documentation/
  repo-actions: [edit, issue, source]
  downloads: [pdf]
  pdf-url: "./docs/Schmidt-Ocean-Institute-Technical-Documentation.pdf"
  cover-image: /images/FKt230115-Falkortoo_Aerial-20230117-Ingle-0824.jpg
  sidebar:
    style: docked
    background: light
    logo: /images/fcs_soibrand_variation3_fullcolorsoibrand_variation3_fullcolor@10x.png
  chapters:
    - index.qmd
    - data_pipeline.qmd
    - data_directory.qmd 
    - dashboards.qmd
    - part: sealog.qmd
      chapters:
        - sealog_subastian.qmd
        - sealog_falkortoo.qmd
  
  appendices:
    - appendix.qmd
    - references.qmd
  

bibliography: references.bib

format:
  html:
    theme:
      light: spacelab
      dark: [darkly, dark.scss]
    css: custom.css
  pdf:
    documentclass: scrbook
    toc: true
    

